import {
  type Action,
  type ActionResult,
  elizaLogger,
  type HandlerCallback,
  type HandlerOptions,
  type IAgentRuntime,
  type Memory,
  ModelType,
  type State,
} from "@elizaos/core";
import type { BrainService } from "../services/brain";
import { handleChainSynthesis } from "../utils/actionChainHelper";

/**
 * PORTED FROM sense-ai-core as a LITERAL COPY of
 * `src/plugins/plugin-senseai/src/actions/analyzeAssetSentiment.ts`.
 *
 * Same contract as the `getNewsDetails` port beside it: the two bodies must answer a sentiment
 * question the SAME way — same ticker extraction, same prompt bytes, same metric block, same
 * billing rule, same synthesis. The analysis itself already lives in the shared Brain
 * (`SentimentEngine.getAssetSentiment`); what is left here is ElizaOS wiring, and wiring is the
 * only place the bodies legitimately differ.
 *
 * Generated by copy/paste (scripts, not by hand) and then edited in exactly TWO places, both
 * marked `ORACLE DIVERGENCE` at their site. Nothing else is touched — not the inline types, not
 * the whitespace inside the extraction prompt.
 *
 * DO NOT RUN PRETTIER ON THIS FILE. It keeps core biome formatting so `diff` against core stays
 * readable and a real change cannot hide in a wall of comma churn. Same convention as
 * `getNewsDetails.ts`, `utils/actionChainHelper.ts` and `utils/withTimeout.ts`.
 *
 *   1. HOW THE LEDGER IS REACHED. core resolves `runtime.getService<SentimentService>("sentiment")`,
 *      whose engine reads `runtime.db` — in the Social body that IS the shared `senseai` cache.
 *      Here it is not: plugin-sql owns `POSTGRES_URL` pointed at the ISOLATED `oracle_agent`
 *      database, which has no sentiment_history table at all. core's line would compile, run,
 *      and query the wrong database. The host injects the real cache handle instead, so this
 *      file goes through BrainService — identical to `getNewsDetails.ts`.
 *
 *   2. NO BROADCASTS_LIVE KILL SWITCH. core opens its handler by refusing to answer when
 *      `BROADCASTS_LIVE=false`, a launch-day switch that keeps the Telegram bot silent while
 *      data syncs. Porting it would mean accepting a paid on-chain prompt and then declining to
 *      answer it — the escrow has already moved, so silence is not free the way it is in a chat
 *      window. The oracle gate is on-chain ($ABLE/escrow), enforced before a prompt is emitted.
 *
 * A NOTE ON THE BILLING RULE, WHICH IS COPIED RATHER THAN FIXED. `getAssetSentiment` returns
 * null both for "this ticker is unsupported" and — because `SentimentEngine` swallows its cache
 * read error and falls through to adapters — for "we could not reach the data". core treats both
 * as an observation and still bills when at least one ticker resolved. On this body that means a
 * partial outage can be charged for on-chain. It is core's contract, not a porting artefact, so
 * it is copied here and raised upstream as CU-86d40mckm rather than forked. Diverging would put
 * the two bodies on different billing rules, which is worse than sharing a known one.
 */
export const analyzeAssetSentimentAction: Action = {
  name: "ANALYZE_ASSET_SENTIMENT",
  similes: [
    "analyze sentiment",
    "fundamental analysis",
    "what is the outlook on",
    "check on-chain data for",
    "is it a good time to buy",
    "check sentiment",
    "analyze this",
    "compare sentiment",
  ],
  description:
    "Triggers a deep fundamental, on-chain, and sentiment analysis for one or more cryptocurrency tokens. Resolves context from conversation history.",

  validate: async () => true,

  handler: async (
    runtime: IAgentRuntime,
    message: Memory,
    state?: State,
    options: HandlerOptions = {},
    callback?: HandlerCallback,
    responses?: Memory[]
  ): Promise<ActionResult> => {
    elizaLogger.info("Executing ANALYZE_ASSET_SENTIMENT action.");

    // ORACLE DIVERGENCE 2 — core's BROADCASTS_LIVE guard sits here and is deliberately absent.
    // See the file header: refusing to answer a prompt the escrow has already charged for is a
    // worse failure than a chat window going quiet.

    // ORACLE DIVERGENCE 1 — the ledger handle. core resolves its SentimentService here; this
    // body resolves BrainService, which delegates to the same Brain engine over the host's
    // connection to the shared cache rather than the isolated oracle_agent database.
    // Kept in core's position (before the try) so the non-billable early return is byte-for-byte
    // core's: an unregistered service is not a failed lookup, and must never read as one.
    const brain = runtime.getService<BrainService>("brain");
    if (!brain) {
      elizaLogger.error("[AnalyzeAssetSentiment] Service missing.");

      return {
        success: false,
        error: "Sentiment service unavailable",
        data: { actionName: "ANALYZE_ASSET_SENTIMENT", isBillable: false },
      };
    }

    try {
      // 1. EXTRACT THE TICKER
      const text = message.content.text || "";
      let tickers: string[] = [];

      // 1. FETCH CONTEXT HISTORY
      // We need this to understand pronouns ("it") or comparisons ("vs ETH")
      const recentMemories = await runtime.getMemories({
        roomId: message.roomId,
        count: 10,
        unique: false,
        tableName: "messages",
      });

      const contextHistory = recentMemories
        .reverse()
        .map((m) => {
          const sender = m.entityId === runtime.agentId ? "Agent" : "User";
          return `${sender}: ${m.content.text}`;
        })
        .join("\n");

      // 2. LLM EXTRACTION
      const extractionPrompt = `
          TASK: Identify the cryptocurrency asset(s) the user wants to analyze based on the conversation context.
          
          CONVERSATION HISTORY:
          ${contextHistory}
          
          CURRENT REQUEST: "${text}"
          
          INSTRUCTIONS:
          1. Get the tickers in relation to the true intent of the CURRENT REQUEST within the CONVERSATION HISTORY context (e.g. "Who made Bitcoin" then "How is its sentiment compared to ETH?", should return ["BTC", "ETH"]).
          2. If the user uses a pronoun like "it", "that", "the coin", or implies a continuation (e.g. "how is the sentiment?"), identify the most recently discussed asset from CONVERSATION HISTORY.
          3. Convert all names to Ticker Symbols (e.g. "Bitcoin" -> "BTC", "Ethereum" -> "ETH").
          4. If no asset can be determined, return an empty array.
          
          OUTPUT JSON:
          { "tickers": ["string"] }
        `;

      const extraction = (await runtime.useModel(ModelType.OBJECT_SMALL, {
        prompt: extractionPrompt,
        schema: {
          type: "object",
          properties: {
            tickers: { type: "array", items: { type: "string" } },
          },
          required: ["tickers"],
        },
      })) as { tickers: string[] };

      tickers = extraction?.tickers?.map((t) => t.toUpperCase()) || [];

      // Clean duplicates
      tickers = [...new Set(tickers)];
      elizaLogger.info(`[AnalyzeAssetSentiment] Extracted tickers: ${JSON.stringify(tickers)}`);

      if (tickers.length === 0) {
        return {
          success: false,
          text: "I couldn't identify which asset you want me to analyze. Please specify a ticker (e.g. BTC).",
          data: { actionName: "ANALYZE_ASSET_SENTIMENT", isBillable: false },
        };
      }

      // Optional: Give user feedback that heavy lifting is happening
      if (callback && message.content.source !== "twitter") {
        await callback({
          text: `Extracting institutional-grade on-chain and sentiment data for ${tickers.join(", ")}...`,
          source: message.content.source,
          thought: `Identified tickers: ${tickers.join(", ")}. Fetching data...`,
        });
      }

      // 2. FETCH DATA FOR ALL TICKERS
      let sentimentObservation =
        "INSTRUCTION: Synthesize a stoic, institutional report based on the below metrics. Explain what they mean for price action and network health. If comparing multiple assets, draw distinct fundamental contrasts.\n";
      const rawDataMap: Record<string, unknown> = {};
      let successfulFetches = 0;

      // Helper function to convert massive numbers to Millions/Billions
      const formatCurrency = (val: number | undefined | null) => {
        if (val === undefined || val === null) return "N/A";
        if (Math.abs(val) >= 1.0e9) return `$${(val / 1.0e9).toFixed(2)}B`;
        if (Math.abs(val) >= 1.0e6) return `$${(val / 1.0e6).toFixed(2)}M`;
        return `$${val.toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
      };

      // Helper to cleanly format raw numbers with commas
      const formatNum = (val: number | undefined | null) => {
        return val !== undefined && val !== null
          ? val.toLocaleString(undefined, { maximumFractionDigits: 2 })
          : "N/A";
      };

      for (const ticker of tickers) {
        elizaLogger.info(`[AnalyzeAssetSentiment] Fetching data for ${ticker}...`);

        const data = await brain.getAssetSentiment(ticker);

        // LOGGING THE DATA PAYLOAD SIZE
        if (data) {
          const dataSize = JSON.stringify(data).length;
          elizaLogger.info(
            `[AnalyzeAssetSentiment] Data received for ${ticker}. Size: ${dataSize} chars.`
          );
        } else {
          elizaLogger.warn(`[AnalyzeAssetSentiment] No data returned for ${ticker}.`);

          sentimentObservation += `\n### INTERNAL LEDGER OBSERVATION: ${ticker}\nI couldn't retrieve robust on-chain or sentiment data for ${ticker}. It is either unsupported or lacks sufficient history.\n`;

          continue;
        }

        successfulFetches++;
        rawDataMap[ticker] = data;

        let ageWarning = "";
        if (data._dataTimestamp) {
          const ageHours = (Date.now() - data._dataTimestamp) / (1000 * 60 * 60);

          if (ageHours > 24) {
            const ageDays = Math.floor(ageHours / 24);
            ageWarning = `\n⚠️ [DATA AGE WARNING]: This data is ${ageDays} day(s) old. Explicitly mention this latency to the user.`;
          }
        }

        // The LLM Prompt Template formatted with STRICT units to prevent hallucination
        sentimentObservation += `
### INTERNAL LEDGER OBSERVATION: ${ticker}${ageWarning}

**[VALUATION & PROFITABILITY]**
- MVRV (30d): ${formatNum(data.mvrv_usd_30d)} ratio (1.0 = breakeven)
- MVRV (365d): ${formatNum(data.mvrv_usd_365d)} ratio (1.0 = breakeven)
- MVRV Z-Score: ${formatNum(data.mvrv_usd_z_score)}
- MVRV Long/Short Diff: ${formatNum(data.mvrv_long_short_diff_usd)}
- Mean Dollar Invested Age: ${formatNum(data.mean_dollar_invested_age)} days
- Mean Realized Price: ${formatCurrency(data.mean_realized_price_usd)}
- NVT Ratio: ${formatNum(data.nvt)}
- Network Profit/Loss: ${formatCurrency(data.network_profit_loss)}
- Realized Value: ${formatCurrency(data.realized_value_usd)}
- Adj. Price DAA Divergence: ${formatNum(data.adjusted_price_daa_divergence)}

**[NETWORK & DEVELOPMENT]**
- Active Addresses (24h): ${formatNum(data.active_addresses_24h)} wallets
- Active Deposits: ${formatNum(data.active_deposits)} wallets
- Active Withdrawals: ${formatNum(data.active_withdrawals)} wallets
- Network Growth: ${formatNum(data.network_growth)} new wallets
- Dev Activity: ${formatNum(data.dev_activity)} events
- Dev Contributors (7d): ${formatNum(data.dev_activity_contributors_count_7d)} developers
- TX Count: ${formatNum(data.transactions_count)}
- TX Volume: ${formatNum(data.transaction_volume)} ${ticker}
- TX Volume P/L Ratio: ${formatNum(data.transaction_volume_profit_loss_ratio)}
- Velocity: ${formatNum(data.velocity)}

**[SMART MONEY & SUPPLY]**
- Age Consumed: ${formatNum(data.age_consumed)} (token-days spike indicator)
- Circulation (1d): ${formatNum(data.circulation_1d)} ${ticker}
- Circulation (365d): ${formatNum(data.circulation_365d)} ${ticker}
- Dormant Circulation (365d): ${formatNum(data.dormant_circulation_365d)} ${ticker}
- Top Holders Amount: ${formatNum(data.amount_in_top_holders)} ${ticker}
- Exchange Top Holders: ${formatNum(data.amount_in_exchange_top_holders)} ${ticker}
- Non-Exchange Top Holders: ${formatNum(data.amount_in_non_exchange_top_holders)} ${ticker}
- Supply on Exchanges: ${data.percent_of_total_supply_on_exchanges ? `${data.percent_of_total_supply_on_exchanges.toFixed(2)}%` : "N/A"}
- Whale TX Count (>100k): ${formatNum(data.whale_transaction_count_100k_usd_to_inf)}
- Whale TX Count (>1M): ${formatNum(data.whale_transaction_count_1m_usd_to_inf)}

**[SOCIAL & HYPE]**
- CFGI Fear & Greed: ${formatNum(data.cfgi_fear_greed_score)}/100 (${data.cfgi_fear_greed_tier ?? "N/A"})
- Social Dominance: ${data.social_dominance_total ? `${data.social_dominance_total.toFixed(2)}%` : "N/A"}
- Social Volume AI: ${formatNum(data.social_volume_ai_total)}
- Trending Words Rank: ${formatNum(data.trending_words_rank)}
- Community Msgs (Telegram): ${formatNum(data.community_messages_count_telegram)}
- Community Msgs (Reddit): ${formatNum(data.community_messages_count_reddit)}
- Sentiment Balance (Total): ${formatNum(data.sentiment_balance_total)}
- Sentiment Balance (Twitter): ${formatNum(data.sentiment_balance_twitter)}
- Sentiment Balance (Telegram): ${formatNum(data.sentiment_balance_telegram)}
- Sentiment Balance (Reddit): ${formatNum(data.sentiment_balance_reddit)}
- Sentiment Balance (Farcaster): ${formatNum(data.sentiment_balance_farcaster)}
- Sentiment Balance (Bitcointalk): ${formatNum(data.sentiment_balance_bitcointalk)}
- Sentiment Balance (4chan): ${formatNum(data.sentiment_balance_4chan)}
- Sentiment Balance (YouTube): ${formatNum(data.sentiment_balance_youtube_videos)}

**[MACRO & DERIVATIVES]**
- Annual Inflation Rate: ${data.annual_inflation_rate ? `${data.annual_inflation_rate.toFixed(2)}%` : "N/A"}
- Gini Index: ${formatNum(data.gini_index)}
- BTC S&P Divergence: ${formatNum(data.btc_s_and_p_price_divergence)}
- Aggregated Funding Rates: ${data.total_funding_rates_aggregated_per_asset ? `${(data.total_funding_rates_aggregated_per_asset * 100).toFixed(4)}%` : "N/A"}
\n`;
      }
      elizaLogger.info(
        `[AnalyzeAssetSentiment] Final Observation Length: ${sentimentObservation.length} chars.`
      );

      const actionResult: ActionResult = {
        success: true,
        text:
          successfulFetches === 0
            ? "I checked the institutional ledger, but I could not retrieve robust on-chain or sentiment data for the requested assets at this time."
            : sentimentObservation,
        data: {
          actionName: "ANALYZE_ASSET_SENTIMENT",
          isBillable: successfulFetches > 0, // Only bill if at least one succeeded
          tickers: tickers,
          rawData: { ...rawDataMap },
        },
      };

      // Call the helper to synthesize if this is the last step
      await handleChainSynthesis(
        runtime,
        message,
        actionResult,
        state,
        options,
        callback,
        responses
      );

      return actionResult;
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      elizaLogger.error("[AnalyzeAssetSentimentAction] Error:", errorMessage);

      return {
        success: false,
        error: errorMessage,
        data: { actionName: "ANALYZE_ASSET_SENTIMENT", isBillable: false },
      };
    }
  },

  examples: [
    [
      {
        name: "{{user}}",
        content: { text: "What's the fundamental outlook on Ethereum?" },
      },
      {
        name: "SenseAI",
        content: {
          text: "Retrieving the on-chain ledger...",
          action: "ANALYZE_ASSET_SENTIMENT",
        },
      },
    ],
    [
      { name: "{{user}}", content: { text: "Is it a good time to buy XBT?" } },
      {
        name: "SenseAI",
        content: {
          text: "Let me check the valuation and smart money flow.",
          action: "ANALYZE_ASSET_SENTIMENT",
        },
      },
    ],
  ],
};
